"""Shared discovery data schemas."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any


@dataclass(frozen=True, slots=True)
class SourceQuery:
    """One source-specific query generated by the query planner."""

    source: str
    query: str
    rationale: str
    priority: int = 1


@dataclass(frozen=True, slots=True)
class Paper:
    """Normalized paper/source record returned by any discovery adapter."""

    title: str
    authors: list[str] = field(default_factory=list)
    year: int | None = None
    doi: str | None = None
    url: str | None = None
    pdf_url: str | None = None
    abstract: str = ""
    source: str = "unknown"
    source_id: str | None = None
    citations_in: list[str] = field(default_factory=list)
    citations_out: list[str] = field(default_factory=list)
    meta: dict[str, Any] = field(default_factory=dict)

    @property
    def key(self) -> str:
        """Stable key for deduplication; prefers DOI, then URL, then title+year."""
        if self.doi:
            return self.doi.lower().strip()
        if self.url:
            return self.url.lower().strip()
        return f"{self.title.lower().strip()}::{self.year}"

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-friendly dict."""
        return {
            "title": self.title,
            "authors": list(self.authors),
            "year": self.year,
            "doi": self.doi,
            "url": self.url,
            "pdf_url": self.pdf_url,
            "abstract": self.abstract,
            "source": self.source,
            "source_id": self.source_id,
            "citations_in": list(self.citations_in),
            "citations_out": list(self.citations_out),
            "meta": dict(self.meta),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Paper:
        """Deserialize from a dict produced by `to_dict`."""
        return cls(
            title=data.get("title", ""),
            authors=list(data.get("authors", [])),
            year=data.get("year"),
            doi=data.get("doi"),
            url=data.get("url"),
            pdf_url=data.get("pdf_url"),
            abstract=data.get("abstract", ""),
            source=data.get("source", "unknown"),
            source_id=data.get("source_id"),
            citations_in=list(data.get("citations_in", [])),
            citations_out=list(data.get("citations_out", [])),
            meta=dict(data.get("meta", {})),
        )


@dataclass(frozen=True, slots=True)
class DuplicateGroup:
    """A cluster of papers judged to be the same work."""

    canonical: Paper
    duplicates: list[Paper] = field(default_factory=list)
    match_reason: str = ""


@dataclass(frozen=True, slots=True)
class ResolveResult:
    """Outcome of resolving a paper to a full-text URL."""

    paper_key: str
    url: str | None
    is_oa: bool
    source: str
    reason: str
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class SearchResult:
    """Result of a single source query."""

    source: str
    query: str
    papers: list[Paper] = field(default_factory=list)
    total: int | None = None
    next_offset: int | None = None
    error: str | None = None
    meta: dict[str, Any] = field(default_factory=dict)
    fetched_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def ok(self) -> bool:
        return self.error is None


@dataclass(frozen=True, slots=True)
class DiscoveryResult:
    """Structured output of the full discovery pipeline."""

    query: str
    plan: dict[str, Any]
    search_results: list[SearchResult]
    deduped_groups: list[DuplicateGroup]
    snowball_papers: list[Paper]
    resolved: list[ResolveResult]
    meta: dict[str, Any] = field(default_factory=dict)
